### ISSUE TITLE
Support for NFC

### ISSUE THREAD

**Issue by maddinkunze** [Joe7500/Builds#3]
Hi Joe, thanks for the nice ROM, i really love it. Is there any way of enabling NFC support for devices with an NFC Chip (i.e. Redmi 9T NFC -> M2010J19SY) or is this feature planned for the future in any way?
Best Regards, Martin

**Comment by Joe7500** [comment]
Hey. 

Ah, the mythical M2010J19SY aka lemon. Unfortunately, I've never seen one in the wild. :)

The NFC kernel driver, service, software etc. are built in and ready to go. However, I don't know if anyone has ever tested it or if it actually works. I also don't  know if you need to enable it somewhere or require an app or something.

If you can provide a full boot logcat, that would be useful to see if the hardware is detected or throws any errors.

Thanks.

**Comment by maddinkunze** [comment]
Should i simply provide a bootlog with your current build of crDroid 10.7 or do you need  something else?

**Comment by Joe7500** [comment]
I had a look and it seems I introduced a bug with NFC in the 10.7 build. Sorry. You can try with crDroid 10.6 or wait for a new build. 

You should be able to toggle NFC on and off in QS or under Settings -> Connected devices -> Connection preferences. Provide logs if it doesn't work.

**Comment by maddinkunze** [comment]
Hi, no problem, thanks for the info. I will let you know whether NFC works in your next automatic build/update and am happy to provide logs if it does not work :)
For later reference: In the current crDroid 10.7 build for Redmi 9T NFC (lemon), NFC is not listed as an option in the settings app, the QS option for NFC is greyed out, long clicking the QS option opens the settings app but it only has the title "NFC" and no content or actual settings.
Thanks for your work and support so far.

**Comment by Joe7500** [comment]
There is a new build available without NFC changes [here](https://sourceforge.net/projects/joes-android-builds/files/crDroid/). 14 firmware recommended. 

I have been advised that NFC still doesn't work. Boot logs would be greatly appreciated.

**Comment by Joe7500** [comment]
Fixed. Test build [here](https://github.com/Joe7500/Builds/releases/tag/Beta). Will be included in the next release.

**Comment by maddinkunze** [comment]
Hey, sorry for the delayed response, my phone broke and it took some time to unlock the replacement and restore my backup.
Just wanted to let you know, that NFC works flawlessly now. Thanks for your great work 👍
Best Regards, Martin
